print('Hello World')
my_name = input('What is your name?: ')
print('It is good to meet you, ' + my_name)
print(f'The length of your name is: {len(my_name)}')
my_age = input('What is you age?: ')
print('You will be ' + str(int(my_age) + 1) + ' in one year')
